### ISSUE TITLE
github file preview broken?

### ISSUE THREAD

**Issue by tlnagy** [JuliaImages/ImageTracking.jl#25]
![image](https://user-images.githubusercontent.com/1661487/74996683-14492c00-5409-11ea-8314-9a1a2b333d3d.png)

Where are all the files? Also, it would be great to have this package registered.

**Comment by zygmuntszpak** [comment]
I find it really odd that you don't see the files. @johnnychen94  Do you see the files or is it broken for you too?

**Comment by johnnychen94** [comment]
It looks normal to me.

**Comment by zygmuntszpak** [comment]
I've put registering the package on my to-do list. Hopefully will have it done next week.

**Comment by johnnychen94** [comment]
This package is now registered.
